In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.2


In [9]:
#Задание 1
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#Задание 2
vector1 = vector[::-1]
print(vector1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
#Задание 3
matrix = np.random.random((5,5))
print(matrix)

[[0.92360506 0.9532217  0.87913234 0.81550315 0.94596055]
 [0.6174988  0.36147315 0.30213582 0.71057099 0.575854  ]
 [0.20852271 0.39685605 0.96668673 0.71579892 0.54393508]
 [0.56995508 0.69327934 0.0506841  0.83361064 0.81820292]
 [0.71987117 0.80502033 0.58267427 0.29517711 0.72678389]]


In [15]:
avr = np.mean(matrix,axis = 1)
print(avr)

[0.90348456 0.51350655 0.5663599  0.59314642 0.62590535]


In [18]:
median = np.median(matrix,axis = 1)
print(median)

[0.92360506 0.575854   0.54393508 0.69327934 0.71987117]


In [33]:
#Задание 4
a = np.array([x for x in range(27)])
a = a.reshape(3,3,3)
print (a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [38]:
#Задание 5
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])
a = a.astype(int)
print (a)

[[3 1 8]
 [4 7 1]]


In [40]:
#Задание 6
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])
a = a.astype(bool)
print(a)

[[ True False False]
 [ True  True  True]
 [False False  True]]


In [42]:
#Задание 7 
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])
a3 = np.hstack((a1,a2))
print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [45]:
#Задание 8
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])
a3 = np.vstack((a1,a2))
print(a3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [52]:
#Задание 9
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
c = np.where(a ==b)
print(c)

(array([0, 3, 4]),)


In [54]:
#Задание 10
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])
c = np.dot(a,b)
print(c)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [57]:
#Задание 11
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
a = np.transpose(a)
print(a)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [62]:
#Задание 12
angles = np.array([3.14, 3.14/2, 6.28])
s = np.sin(angles)
print(s)

[ 0.00159265  0.99999968 -0.0031853 ]
